-- Copyright (c) 2026 Paul Butcher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
-- Generated by scripts/generate_guards.pl from test/vendor/GFM/regression.json (split by each
-- example's fence-line extension tag, see test/vendor/README.md); do not edit by hand.
import CheckExample
import CheckExampleGfm

#guard checkExample 1 "Regression tests" "line1\r\r\nline2\n" "<p>line1</p>\n<p>line2</p>\n"
#guard checkExample 2 "Regression tests" "By taking it apart\n\n- alternative solutions\n\t\nRepeatedly solving\n\t\n- how techniques\n" "<p>By taking it apart</p>\n<ul>\n<li>alternative solutions</li>\n</ul>\n<p>Repeatedly solving</p>\n<ul>\n<li>how techniques</li>\n</ul>\n"
#guard checkExample 3 "Regression tests" "<h1>lorem</h1>\n\n<h2>lorem</h2>\n\n<h3>lorem</h3>\n\n<h4>lorem</h4>\n\n<h5>lorem</h5>\n\n<h6>lorem</h6>\n" "<h1>lorem</h1>\n<h2>lorem</h2>\n<h3>lorem</h3>\n<h4>lorem</h4>\n<h5>lorem</h5>\n<h6>lorem</h6>\n"
#guard checkExample 4 "Regression tests" "hi\n--\t\n" "<h2>hi</h2>\n"
#guard checkExample 5 "Regression tests" "a***b* c*\n" "<p>a*<em><em>b</em> c</em></p>\n"
#guard checkExample 6 "Regression tests" "[a]\n\n[a]: <te<st>\n" "<p>[a]</p>\n<p>[a]: &lt;te<st></p>\n"
#guard checkExample 7 "Regression tests" "[a](te\\ st)\n" "<p>[a](te\\ st)</p>\n"
#guard checkExampleGfm 8 "Regression tests" "~~**_`this`_**~~  \n~~***`this`***~~  \n~~___`this`___~~\n\n**_`this`_**  \n***`this`***  \n___`this`___\n\n~~**_this_**~~  \n~~***this***~~  \n~~___this___~~\n\n**_this_**  \n***this***  \n___this___\n" "<p><del><strong><em><code>this</code></em></strong></del><br />\n<del><em><strong><code>this</code></strong></em></del><br />\n<del><em><strong><code>this</code></strong></em></del></p>\n<p><strong><em><code>this</code></em></strong><br />\n<em><strong><code>this</code></strong></em><br />\n<em><strong><code>this</code></strong></em></p>\n<p><del><strong><em>this</em></strong></del><br />\n<del><em><strong>this</strong></em></del><br />\n<del><em><strong>this</strong></em></del></p>\n<p><strong><em>this</em></strong><br />\n<em><strong>this</strong></em><br />\n<em><strong>this</strong></em></p>\n"
#guard checkExample 9 "Regression tests" "City:\n<span itemprop=\"contentLocation\" itemscope itemtype=\"https://schema.org/City\">\n  <meta itemprop=\"name\" content=\"Springfield\">\n</span>\n" "<p>City:\n<span itemprop=\"contentLocation\" itemscope itemtype=\"https://schema.org/City\">\n<meta itemprop=\"name\" content=\"Springfield\">\n</span></p>\n"
#guard checkExampleGfm 10 "Regression tests" "~Hi~ Hello, world!\n" "<p><del>Hi</del> Hello, world!</p>\n"
#guard checkExampleGfm 11 "Regression tests" "This ~text~ ~~is~~ ~~~curious~~~.\n" "<p>This <del>text</del> <del>is</del> ~~~curious~~~.</p>\n"
#guard checkExample 12 "Regression tests" "[x](http://members.aon.at/~nkehrer/ibm_5110/emu5110.html)\n" "<p><a href=\"http://members.aon.at/~nkehrer/ibm_5110/emu5110.html\">x</a></p>\n"
-- Example 13 ("table footnotes") needs footnotes, not yet implemented; excluded rather than
-- left in to fail (see test/vendor/README.md).
#guard checkExample 14 "Regression tests" "City:\n<span itemprop=\"contentLocation\" itemscope itemtype=\"https://schema.org/City\">\n  <meta itemprop=\"name\" content=\"Springfield\">\n</span>\n" "<p>City:\n<span itemprop=\"contentLocation\" itemscope itemtype=\"https://schema.org/City\">\n<meta itemprop=\"name\" content=\"Springfield\">\n</span></p>\n"
#guard checkExample 15 "Regression tests" "[a](\\ b)\n\n[a](<<b)\n\n[a](<b\n)\n" "<p>[a](\\ b)</p>\n<p>[a](&lt;&lt;b)</p>\n<p>[a](&lt;b\n)</p>\n"
#guard checkExample 16 "Regression tests" "[link](url ((title))\n" "<p>[link](url ((title))</p>\n"
#guard checkExample 17 "Regression tests" "</script>\n\n</pre>\n\n</style>\n" "</script>\n</pre>\n</style>\n"
#guard checkExample 18 "Regression tests" "[a](<b) c>\n" "<p>[a](&lt;b) c&gt;</p>\n"
#guard checkExampleGfm 19 "Regression tests" "|\n-|\n" "<p>|\n-|</p>\n"
-- Examples 20-25 all need footnotes; excluded for the same reason as example 13.
#guard checkExample 26 "Regression tests" "*text* [link](#section)\n" "<p><em>text</em> <a href=\"#section\">link</a></p>\n"
