-- Copyright (c) 2026 Paul Butcher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
-- Generated by scripts/generate_guards.pl from test/vendor/md4c/spec-latex-math.json; do not edit by hand.
module

public import CheckExampleMath
meta import CheckExampleMath

@[expose] public section

#guard checkExampleMath 1 "LaTeX Math" "$a+b=c$ Hello, world!\n" "<p><span class=\"math inline\">\\(a+b=c\\)</span> Hello, world!</p>\n"
#guard checkExampleMath 2 "LaTeX Math" "$$foo $bar$ baz$$\n" "<p>$$foo <span class=\"math inline\">\\(bar\\)</span> baz$$</p>\n"
#guard checkExampleMath 3 "LaTeX Math" "x$a+b=c$\n" "<p>x$a+b=c$</p>\n"
#guard checkExampleMath 4 "LaTeX Math" "$a+b=c$x\n" "<p>$a+b=c$x</p>\n"
#guard checkExampleMath 5 "LaTeX Math" "This is a display equation: $$\\int_a^b x dx$$.\n" "<p>This is a display equation: <span class=\"math display\">\\[\\int_a^b x dx\\]</span>.</p>\n"
#guard checkExampleMath 6 "LaTeX Math" "$$\n\\int_a^b\nf(x) dx\n$$\n" "<p><span class=\"math display\">\\[ \\int_a^b f(x) dx \\]</span></p>\n"
