name = "commonmark"
version = "0.1.0"
defaultTargets = ["CommonMark"]
testDriver = "test"

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "v4.32.0"

[[lean_lib]]
name = "CommonMark"

[[lean_lib]]
name = "TestData"
srcDir = "test"
globs = ["SpecExamples", "Conformance"]

[[lean_exe]]
name = "test"
srcDir = "test"
root = "Main"
