#!/usr/bin/env perl
# Generates one `#guard` per example from a vendored spec.json-shaped file (see
# extract_spec.pl). Defaults to test/SpecGuards.lean's own checkExample/CheckExample; pass
# a different checker function and import module to generate against another entry point
# (e.g. checkExampleGfm/CheckExampleGfm for the GFM variant).
use strict;
use warnings;
use utf8;
use JSON::PP qw(decode_json);
binmode(STDOUT, ':encoding(UTF-8)');

my ($specfile, $checker, $import) = @ARGV;
die "usage: generate_guards.pl <spec.json> [checker] [import]\n" unless defined $specfile;
$checker //= 'checkExample';
$import //= 'CheckExample';

open(my $fh, '<:raw', $specfile) or die "cannot open $specfile: $!";
local $/;
my $json = <$fh>;
close($fh);

my $tests = decode_json($json);

sub lean_string {
    my ($s) = @_;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    $s =~ s/\t/\\t/g;
    $s =~ s/\r/\\r/g;
    $s =~ s/\n/\\n/g;
    $s =~ s/([\x00-\x1f])/sprintf('\u%04x', ord($1))/ge;
    return $s;
}

print <<HEADER;
-- Copyright (c) 2026 Paul Butcher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
-- Generated by scripts/generate_guards.pl from $specfile; do not edit by hand.
import $import

HEADER

for my $t (@$tests) {
    print "#guard $checker " . $t->{example}
        . ' "' . lean_string($t->{section}) . '"'
        . ' "' . lean_string($t->{markdown}) . '"'
        . ' "' . lean_string($t->{html}) . "\"\n";
}
