#!/usr/bin/env perl
# Generates test/SpecGuards.lean, one `#guard` per example, from the vendored
# test/vendor/CommonMark/spec.json. Re-run after refreshing spec.json (see extract_spec.pl).
use strict;
use warnings;
use utf8;
use JSON::PP qw(decode_json);
binmode(STDOUT, ':encoding(UTF-8)');

my ($specfile) = @ARGV;
die "usage: generate_guards.pl <spec.json>\n" unless defined $specfile;

open(my $fh, '<:raw', $specfile) or die "cannot open $specfile: $!";
local $/;
my $json = <$fh>;
close($fh);

my $tests = decode_json($json);

sub lean_string {
    my ($s) = @_;
    $s =~ s/\\/\\\\/g;
    $s =~ s/"/\\"/g;
    $s =~ s/\t/\\t/g;
    $s =~ s/\r/\\r/g;
    $s =~ s/\n/\\n/g;
    $s =~ s/([\x00-\x1f])/sprintf('\u%04x', ord($1))/ge;
    return $s;
}

print <<'HEADER';
-- Copyright (c) 2026 Paul Butcher. All rights reserved.
-- Released under Apache 2.0 license as described in the file LICENSE.
-- Generated by scripts/generate_guards.pl from test/vendor/CommonMark/spec.json; do not edit by hand.
import CheckExample

HEADER

for my $t (@$tests) {
    print '#guard checkExample ' . $t->{example}
        . ' "' . lean_string($t->{section}) . '"'
        . ' "' . lean_string($t->{markdown}) . '"'
        . ' "' . lean_string($t->{html}) . "\"\n";
}
